#ehcache配置
ehcache:
  heap: 1000 #堆内存缓存个数
  offHeap: 100 #堆外内存存储大小MB
  disk: 30  #磁盘数据大小
  diskDir: /Users/yj/ehcache #磁盘存储路径
  cacheNames:   #配置缓存实例个数
    - user
    - item
    - card

spring:
  cache:
    type: ehcache